version: '3'
services:

  db:
    image: postgres:14.6-alpine
    container_name: db
    networks: 
      - net
    volumes:
      - ./data/db:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      

  bot:
    build: ./bot
    container_name: bot
    networks: 
      - net
    environment:
      - URL=http://practic:7000
    restart: unless-stopped
    

  practic:
    build: 
      context: ./practic
      dockerfile: Dockerfile.dev
      
    command: python manage.py runserver 0.0.0.0:7000 #--settings='config.settings.dev'
    restart: unless-stopped
    env_file:
      - ./practic/.env
    networks: 
      - net
    container_name: practic
    
     
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

   
  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    container_name: redis
    networks: 
      - net

  worker:
    build:
      context: ./practic
      dockerfile: Dockerfile.dev
    container_name: worker
    hostname: worker
    networks: 
      - net
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - worker_vol:/practic/practic
    links:
      - redis
    depends_on:
      - redis
      - db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  flower:
    build:
      context: ./practic
      dockerfile: Dockerfile.dev
    hostname: flower
    networks: 
      - net
    container_name: flower
    entrypoint: celery
    command: -A celery_app.app flower --loglevel=info
    volumes:
      - flower_vol:/practic/practic
    links:
      - redis
    depends_on:
      - redis

  scheduler:
    build:
      context: ./practic
      dockerfile: Dockerfile.dev
    hostname: scheduler
    networks: 
      - net
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    container_name: scheduler
    volumes:
      - scheduler_vol:/practic/practic
    links:
      - redis
    depends_on:
      - redis
      - worker

volumes:
  static_vol:
  worker_vol:
  flower_vol:
  scheduler_vol:

networks:
  net:
    driver: bridge
