# Generated by Django 5.0.6 on 2024-06-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_post_comment_cel_islam_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='islam',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vred_privichki',
        ),
        migrations.AddField(
            model_name='islam',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='islams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vredprivichki',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vredprivichkis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
