# Generated by Django 5.0.6 on 2024-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_user_islam_remove_user_vred_privichki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cel',
            name='dt_end',
            field=models.DateField(null=True),
        ),
    ]
