# Generated by Django 5.0.6 on 2024-06-10 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_cel_dt_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cels', to=settings.AUTH_USER_MODEL),
        ),
    ]
