# Generated by Django 5.0.6 on 2024-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islam',
            name='mechet_fard',
            field=models.BooleanField(),
        ),
    ]
